export enum WatchlistStatus {
  PLAN_TO_WATCH = 'PLAN_TO_WATCH',
  WATCHING = 'WATCHING',
  COMPLETED = 'COMPLETED',
  DROPPED = 'DROPPED',
}

export enum RecommendationSource {
  AI_HYBRID = 'AI_HYBRID',
  SEMANTIC_SEARCH = 'SEMANTIC_SEARCH',
  BEHAVIOR_PROFILE = 'BEHAVIOR_PROFILE',
  AI_ASSISTANT = 'AI_ASSISTANT',
  TRENDING = 'TRENDING',
}
